Feature: Search

Background:
 	Given User has successful logged in
 	
#@KeywordSearch
#Scenario: TC_KeywordSearch_01 : Search for an Acronym as "gdp"
#Given User enters keyword "gdp"
#Then User verify keyword search results 
# 	
#@KeywordSearch
#Scenario: TC_KeywordSearch_02 : Search for an Acronym as "PMI" 
#Given User enters keyword "PMI"
#Then User verify keyword search results
#
#@KeywordSearch 
#Scenario: TC_KeywordSearch_03 : Search for an Acronym as "FLA"
#Given User enters keyword "FLA"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_04 : Search for an Acronym as "cpi"
#Given User enters keyword "cpi"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_05 : Search for an Acronym as "EFTA"
#Given User enters keyword "EFTA"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_06 : Search for an Acronym as "GIO"
#Given User enters keyword "GIO"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_07 : Search for an Acronym as "MMA"
#Given User enters keyword "MMA"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_08 : Search for an Acronym as "FAI"
#Given User enters keyword "FAI"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_09 : Search for an Acronym as "fdi"
#Given User enters keyword "fdi"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_10 : Search for an Acronym as "GCF"
#Given User enters keyword "GCF"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_11 : Search for an Acronym as "imf"
#Given User enters keyword "imf"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_12 : Search for an Acronym as "SOE"
#Given User enters keyword "SOE"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_13 : Search for an Acronym as "fob"
#Given User enters keyword "fob"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_14 : Search for an Acronym as "gnp"
#Given User enters keyword "gnp"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_15 : Search for an Acronym as "ppp"
#Given User enters keyword "ppp"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_16 : Search for an Acronym as "lcd"
#Given User enters keyword "lcd"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_17 : Search for an Acronym as "PCE"
#Given User enters keyword "PCE"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_18 : Search for an Acronym as "bis"
#Given User enters keyword "bis"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_19 : Search for an Acronym as "QFII"
#Given User enters keyword "QFII"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_20 : Search for an Acronym as "icbc"
#Given User enters keyword "icbc"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_21 : Search for an Acronym as "ipi"
#Given User enters keyword "ipi"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_22 : Search for an Acronym as "ytd"
#Given User enters keyword "ytd"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_23 : Search for an Acronym as "NPL"
#Given User enters keyword "NPL"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_24 : Search for an Acronym as "usd"
#Given User enters keyword "usd"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_25 : Search for an Acronym as "yoy"
#Given User enters keyword "yoy"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_26 : Search for an Acronym as "mfg"
#Given User enters keyword "mfg"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_27 : Search for an Acronym as "crb"
#Given User enters keyword "crb"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_28 : Search for an Acronym as "ism"
#Given User enters keyword "ism"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_29 : Search for an Acronym as "avg"
#Given User enters keyword "avg"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_30 : Search for an Acronym as "wti"
#Given User enters keyword "wti"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_31 : Search for an Acronym as "fed"
#Given User enters keyword "fed"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_32 : Search for an Acronym as "atm"
#Given User enters keyword "atm"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_33 : Search for an Acronym as "eu"
#Given User enters keyword "eu"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_34 : Search for an Acronym as "bdi"
#Given User enters keyword "bdi"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_35 : Search for an Acronym as "r&d"
#Given User enters keyword "r&d"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_36 : Search for an Acronym as "excl"
#Given User enters keyword "excl"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_37 : Search for an Acronym as "sme"
#Given User enters keyword "sme"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_38 : Search for an Acronym as "ipo"
#Given User enters keyword "ipo"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_39 : Search for an Acronym as "CAP"
#Given User enters keyword "CAP"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_40 : Search for an Acronym as "iti"
#Given User enters keyword "iti"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_41 : Search for an Acronym as "ind"
#Given User enters keyword "ind"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_42 : Search for an Acronym as "us"
#Given User enters keyword "us"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_43 : Search for an Acronym as "gni"
#Given User enters keyword "gni"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_44 : Search for an Acronym as "eur"
#Given User enters keyword "eur"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_45 : Search for an Acronym as "s&p"
#Given User enters keyword "s&p"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_46 : Search for an Acronym as "lng"
#Given User enters keyword "lng"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_47 : Search for an Acronym as "cif"
#Given User enters keyword "cif"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_48 : Search for an Acronym as "bsi"
#Given User enters keyword "bsi"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_49 : Search for an Acronym as "teu"
#Given User enters keyword "teu"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_50 : Search for an Acronym as "no"
#Given User enters keyword "no"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_51 : Search for an Acronym as "dc"
#Given User enters keyword "dc"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_52 : Search for an Acronym as "WPI"
#Given User enters keyword "WPI"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_53 : Search for an Acronym as "sitc"
#Given User enters keyword "sitc"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_54 : Search for an Acronym as "ifs"
#Given User enters keyword "ifs"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_55 : Search for an Acronym as "opec"
#Given User enters keyword "opec"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_56 : Search for an Acronym as "iip"
#Given User enters keyword "iip"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_57: Search for an Acronym as "ecb"
#Given User enters keyword "ecb"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_58: Search for an Acronym as "wsa"
#Given User enters keyword "wsa"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_59 : Search for an Acronym as "LME"
#Given User enters keyword "LME"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_60 : Search for an Acronym as "incl"
#Given User enters keyword "incl"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_61 : Search for an Acronym as "fii"
#Given User enters keyword "fii"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_62 : Search for an Acronym as "hicp"
#Given User enters keyword "hicp"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_63 : Search for an Acronym as "vai"
#Given User enters keyword "vai"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_64 : Search for an Acronym as "sdr"
#Given User enters keyword "sdr"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_65 : Search for an Acronym as "vol"
#Given User enters keyword "vol"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_66 : Search for an Acronym as "corp"
#Given User enters keyword "corp"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_67 : Search for an Acronym as "rev"
#Given User enters keyword "rev"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_68 : Search for an Acronym as "frb"
#Given User enters keyword "frb"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_69 : Search for an Acronym as "abs"
#Given User enters keyword "abs"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_70 : Search for an Acronym as "gva"
#Given User enters keyword "gva"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_71 : Search for an Acronym as "gov"
#Given User enters keyword "gov"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_72 : Search for an Acronym as "nim"
#Given User enters keyword "nim"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_73 : Search for an Acronym as "cfetc"
#Given User enters keyword "cfetc"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_74 : Search for an Acronym as "uae"
#Given User enters keyword "uae"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_75 : Search for an Acronym as "rpi"
#Given User enters keyword "rpi"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_76 : Search for an Acronym as "roa"
#Given User enters keyword "roa"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_77 : Search for an Acronym as "gsdp"
#Given User enters keyword "gsdp"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_78 : Search for an Acronym as "cny"
#Given User enters keyword "cny"
#Then User verify keyword search results

@KeywordSearch
Scenario: TC_KeywordSearch_79 : Search for an Acronym as "idr"
Given User enters keyword "idr"
Then User verify keyword search results

@KeywordSearch
Scenario: TC_KeywordSearch_80 : Search for an Acronym as "ccb"
Given User enters keyword "ccb"
Then User verify keyword search results

@KeywordSearch
Scenario: TC_KeywordSearch_81 : Search for an Acronym as "arpu"
Given User enters keyword "arpu"
Then User verify keyword search results

@KeywordSearch
Scenario: TC_KeywordSearch_82 : Search for an Acronym as "sna"
Given User enters keyword "sna"
Then User verify keyword search results

@KeywordSearch
Scenario: TC_KeywordSearch_83 : Search for an Acronym as "sa"
Given User enters keyword "sa"
Then User verify keyword search results

@KeywordSearch
Scenario: TC_KeywordSearch_84 : Search for an Acronym as "nibfc"
Given User enters keyword "nibfc"
Then User verify keyword search results

@KeywordSearch
Scenario: TC_KeywordSearch_85 : Search for an Acronym as "cpo"
Given User enters keyword "cpo"
Then User verify keyword search results

@KeywordSearch
Scenario: TC_KeywordSearch_86 : Search for an Acronym as "mpi"
Given User enters keyword "mpi"
Then User verify keyword search results

@KeywordSearch
Scenario: TC_KeywordSearch_87 : Search for an Acronym as "inst"
Given User enters keyword "inst"
Then User verify keyword search results

@KeywordSearch
Scenario: TC_KeywordSearch_88 : Search for an Acronym as "eu27"
Given User enters keyword "eu27"
Then User verify keyword search results

@KeywordSearch
Scenario: TC_KeywordSearch_89 : Search for an Acronym as "crr"
Given User enters keyword "crr"
Then User verify keyword search results

@KeywordSearch
Scenario: TC_KeywordSearch_90 : Search for an Acronym as "99p"
Given User enters keyword "99p"
Then User verify keyword search results

#@KeywordSearch
#Scenario: TC_KeywordSearch_91 : Search for an Acronym as "2005p"
#Given User enters keyword "2005p"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_92: Search for an Acronym as "sea"
#Given User enters keyword "sea"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_93 : Search for an Acronym as "sbr"
#Given User enters keyword "sbr"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_94 : Search for an Acronym as "ois"
#Given User enters keyword "ois"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_95 : Search for an Acronym as "jpy"
#Given User enters keyword "jpy"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_96 : Search for an Acronym as "rpk"
#Given User enters keyword "rpk"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_97 : Search for an Acronym as "ron"
#Given User enters keyword "ron"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_98 : Search for an Acronym as "adp"
#Given User enters keyword "adp"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_99 : Search for an Acronym as "ASEAN"
#Given User enters keyword "ASEAN"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_100 : Search for an Acronym as "Auto"
#Given User enters keyword "Auto"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_101 : Search for an Acronym as "Average Annual Wage"
#Given User enters keyword "Average Annual Wage"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_102 : Search for an Acronym as "BCI"
#Given User enters keyword "BCI"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_103 : Search for an Acronym as "bdo"
#Given User enters keyword "bdo"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_104 : Search for an Acronym as "bldg"
#Given User enters keyword "bldg"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_105 : Search for an Acronym as "BLS"
#Given User enters keyword "BLS"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_106 : Search for an Acronym as "BOP"
#Given User enters keyword "BOP"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_107 : Search for an Acronym as "BPM6"
#Given User enters keyword "BPM6"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_108 : Search for an Acronym as "BPM5"
#Given User enters keyword "BPM5"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_109 : Search for an Acronym as "BRIC"
#Given User enters keyword "BRIC"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_110 : Search for an Acronym as "Call Market Rate"
#Given User enters keyword "Call Market Rate"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_111 : Search for an Acronym as "cbi"
#Given User enters keyword "cbi"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_112: Search for an Acronym as "cci"
#Given User enters keyword "cci"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_113 : Search for an Acronym as "CD"
#Given User enters keyword "CD"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_114 : Search for an Acronym as "CDS"
#Given User enters keyword "CDS"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_115 : Search for an Acronym as "cgpi"
#Given User enters keyword "cgpi"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_116 : Search for an Acronym as "Cil"
#Given User enters keyword "Cil"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_117 : Search for an Acronym as "Cis"
#Given User enters keyword "Cis"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_118 : Search for an Acronym as "cli"
#Given User enters keyword "cli"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_119 : Search for an Acronym as "cn"
#Given User enters keyword "cn"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_120 : Search for an Acronym as "cnh"
#Given User enters keyword "cnh"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_121 : Search for an Acronym as "ccfi"
#Given User enters keyword "ccfi"
#Then  User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_122 : Search for an Acronym as "Condo"
#Given User enters keyword "Condo"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_123 : Search for an Acronym as "convenience store"
#Given User enters keyword "convenience store"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_124 : Search for an Acronym as "Cr"
#Given User enters keyword "Cr"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_125 : Search for an Acronym as "csi"
#Given User enters keyword "csi"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_126 : Search for an Acronym as "CSRC"
#Given User enters keyword "CSRC"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_127 : Search for an Acronym as "current account deficit"
#Given User enters keyword "current account deficit"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_128 : Search for an Acronym as "dbu"
#Given User enters keyword "dbu"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_129 : Search for an Acronym as "dcs"
#Given User enters keyword "dcs"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_130 : Search for an Acronym as "Dr"
#Given User enters keyword "Dr"
#Then User verify keyword search results
#
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_131 : Search for an Acronym as "EEI"
#Given User enters keyword "EEI"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_132 : Search for an Acronym as "enrollment"
#Given User enters keyword "enrollment"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_133 : Search for an Acronym as "eps"
#Given User enters keyword "eps"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_134 : Search for an Acronym as "EURIBOR"
#Given User enters keyword "EURIBOR"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_135 : Search for an Acronym as "ExPI"
#Given User enters keyword "ExPI"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_136 : Search for an Acronym as "FDA"
#Given User enters keyword "FDA"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_137 : Search for an Acronym as "fao"
#Given User enters keyword "fao"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_138 : Search for an Acronym as "fas"
#Given User enters keyword "fas"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_139 : Search for an Acronym as "fce"
#Given User enters keyword "fce"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_140 : Search for an Acronym as "Fed rate"
#Given User enters keyword "Fed rate"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_141 : Search for an Acronym as "FTSE"
#Given User enters keyword "FTSE"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_142 : Search for an Acronym as "FTZ"
#Given User enters keyword "FTZ"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_143 : Search for an Acronym as "FX"
#Given User enters keyword "FX"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_144 : Search for an Acronym as "G7"
#Given User enters keyword "G7"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_145 : Search for an Acronym as "GCE"
#Given User enters keyword "GCE"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_146 : Search for an Acronym as "GDP constant"
#Given User enters keyword "GDP constant"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_147 : Search for an Acronym as "GFCF"
#Given User enters keyword "GFCF"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_148 : Search for an Acronym as "hh"
#Given User enters keyword "hh"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_149 : Search for an Acronym as "HIBOR"
#Given User enters keyword "HIBOR"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_150 : Search for an Acronym as "hk"
#Given User enters keyword "hk"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_151 : Search for an Acronym as "HS"
#Given User enters keyword "HS"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_152 : Search for an Acronym as "IDA"
#Given User enters keyword "IDA"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_153 : Search for an Acronym as "ICI"
#Given User enters keyword "ICI"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_154 : Search for an Acronym as "IDI"
#Given User enters keyword "IDI"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_155 : Search for an Acronym as "ImPI"
#Given User enters keyword "ImPI"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_156 : Search for an Acronym as "info"
#Given User enters keyword "info"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_157 : Search for an Acronym as "inv"
#Given User enters keyword "inv"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_158 : Search for an Acronym as "Internet shopping"
#Given User enters keyword "Internet shopping"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_159 : Search for an Acronym as "IP"
#Given User enters keyword "IP"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_160 : Search for an Acronym as "jsx"
#Given User enters keyword "jsx"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_161 : Search for an Acronym as "Labor"
#Given User enters keyword "Labor"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_162 : Search for an Acronym as "Lao"
#Given User enters keyword "Lao"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_163 : Search for an Acronym as "l&d"
#Given User enters keyword "l&d"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_164 : Search for an Acronym as "LIBOR"
#Given User enters keyword "LIBOR"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_165 : Search for an Acronym as "LMRA"
#Given User enters keyword "LMRA"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_166 : Search for an Acronym as "Loan"
#Given User enters keyword "Loan"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_167 : Search for an Acronym as "lpg"
#Given User enters keyword "lpg"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_168 : Search for an Acronym as "Money Supply"
#Given User enters keyword "Money Supply"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_169 : Search for an Acronym as "M&A"
#Given User enters keyword "M&A"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_170 : Search for an Acronym as "mfi"
#Given User enters keyword "mfi"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_171 : Search for an Acronym as "mfsm"
#Given User enters keyword "mfsm"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_172 : Search for an Acronym as "MOHRSS"
#Given User enters keyword "MOHRSS"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_173 : Search for an Acronym as "mkt"
#Given User enters keyword "mkt"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_174 : Search for an Acronym as "Market cap"
#Given User enters keyword "Market cap"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_175 : Search for an Acronym as "Migrant"
#Given User enters keyword "Migrant"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_176 : Search for an Acronym as "MLF"
#Given User enters keyword "MLF"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_177 : Search for an Acronym as "mom"
#Given User enters keyword "mom"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_178 : Search for an Acronym as "movie"
#Given User enters keyword "movie"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_179 : Search for an Acronym as "nbs"
#Given User enters keyword "nbs"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_180 : Search for an Acronym as "ncd"
#Given User enters keyword "ncd"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_181 : Search for an Acronym as "ndf"
#Given User enters keyword "ndf"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_182 : Search for an Acronym as "ndi"
#Given User enters keyword "ndi"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_183 : Search for an Acronym as "NEER"
#Given User enters keyword "NEER"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_184 : Search for an Acronym as "npa"
#Given User enters keyword "npa"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_185 : Search for an Acronym as "NYSE"
#Given User enters keyword "NYSE"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_186 : Search for an Acronym as "ODI"
#Given User enters keyword "ODI"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_187 : Search for an Acronym as "oecd"
#Given User enters keyword "oecd"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_188 : Search for an Acronym as "OMO"
#Given User enters keyword "OMO"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_189 : Search for an Acronym as "OTC"
#Given User enters keyword "OTC"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_190 : Search for an Acronym as "pa"
#Given User enters keyword "pa"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_191 : Search for an Acronym as "pbc"
#Given User enters keyword "pbc"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_192 : Search for an Acronym as "PDI"
#Given User enters keyword "PDI"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_193 : Search for an Acronym as "p/e"
#Given User enters keyword "p/e"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_194 : Search for an Acronym as "pkr"
#Given User enters keyword "pkr"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_195 : Search for an Acronym as "pvc"
#Given User enters keyword "pvc"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_196 : Search for an Acronym as "PVI"
#Given User enters keyword "PVI"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_197 : Search for an Acronym as "QDII"
#Given User enters keyword "QDII"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_198 : Search for an Acronym as "qoq"
#Given User enters keyword "qoq"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_199 : Search for an Acronym as "qtr"
#Given User enters keyword "qtr"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_200 : Search for an Acronym as "Reit"
#Given User enters keyword "Reit"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_201 : Search for an Acronym as "REER"
#Given User enters keyword "REER"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_202 : Search for an Acronym as "repo"
#Given User enters keyword "repo"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_203 : Search for an Acronym as "RD"
#Given User enters keyword "RD"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_204 : Search for an Acronym as "Roe"
#Given User enters keyword "Roe"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_205 : Search for an Acronym as "ROW"
#Given User enters keyword "ROW"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_206 : Search for an Acronym as "RQFII"
#Given User enters keyword "RQFII"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_207 : Search for an Acronym as "rrr"
#Given User enters keyword "rrr"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_208 : Search for an Acronym as "Russia"
#Given User enters keyword "Russia"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_209 : Search for an Acronym as "sgx"
#Given User enters keyword "sgx"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_210 : Search for an Acronym as "SHIBOR"
#Given User enters keyword "SHIBOR"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_211 : Search for an Acronym as "sia"
#Given User enters keyword "sia"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_212 : Search for an Acronym as "slf"
#Given User enters keyword "slf"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_213 : Search for an Acronym as "spf"
#Given User enters keyword "spf"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_214 : Search for an Acronym as "SSF"
#Given User enters keyword "SSF"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_215 : Search for an Acronym as "T-bill"
#Given User enters keyword "T-bill"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_216 : Search for an Acronym as "TOT"
#Given User enters keyword "TOT"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_217 : Search for an Acronym as "TFR"
#Given User enters keyword "TFR"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_218 : Search for an Acronym as "Tfp"
#Given User enters keyword "Tfp"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_219 : Search for an Acronym as "tse"
#Given User enters keyword "tse"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_220 : Search for an Acronym as "UN"
#Given User enters keyword "UN"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_221 : Search for an Acronym as "UVI"
#Given User enters keyword "UVI"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_222 : Search for an Acronym as "gds"
#Given User enters keyword "gds"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_223 : Search for an Acronym as "wmp"
#Given User enters keyword "wmp"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_224 : Search for an Acronym as "WR"
#Given User enters keyword "WR"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_225 : Search for an Acronym as "PSI"
#Given User enters keyword "PSI"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_226 : Search for an Acronym as "PE"
#Given User enters keyword "PE"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_227 : Search for an Acronym as "ppi"
#Given User enters keyword "ppi"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_228 : Search for an Acronym as "SUV"
#Given User enters keyword "SUV"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_229 : Search for an Acronym as "X"
#Given User enters keyword "X"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_230 : Search for an Acronym as "VaR"
#Given User enters keyword "VaR"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_231 : Search for an Acronym as "VAT"
#Given User enters keyword "VAT"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_232 : Search for an Acronym as "Pondicherry"
#Given User enters keyword "Pondicherry"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_233 : Search for an Acronym as "Kolkata"
#Given User enters keyword "Kolkata"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_234 : Search for an Acronym as "Odisha"
#Given User enters keyword "Odisha"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_235 : Search for an Acronym as "Mumbai"
#Given User enters keyword "Mumbai"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_236 : Search for an Acronym as "Madras"
#Given User enters keyword "Madras"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_237 
#Given User enters keyword "Electricity AND gas AND India"
#Then  User verifies keyword search results 
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_238
#Given User enters keyword "Electricity and gas and India"
#Then  User verifies keyword search results 
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_239
#Given User enters keyword "Electricity AND gas and India"
#Then  User verifies keyword search results 
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_240
#Given User enters keyword "oil OR water OR industry"
#Then  User verifies keyword search results 
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_241
#Given User enters keyword "oil or water OR industry"
#Then  User verifies keyword search results 
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_242
#Given User enters keyword "oil or water or industry"
#Then  User verifies keyword search results 
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_243
#Given User enters keyword "capital NOT price NOT Algeria"
#Then  User verifies keyword search results 
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_244
#Given User enters keyword "capital not price not Algeria"
#Then  User verifies keyword search results 
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_245
#Given User enters keyword "capital NOT price not Algeria"
#Then  User verifies keyword search results 
# 
#@KeywordSearch
#Scenario: TC_KeywordSearch_246
#Given User enters keyword "capital AND price OR Algeria"
#Then  User verifies keyword search results 
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_247
#Given User enters keyword "capital and price OR Algeria"
#Then  User verifies keyword search results 
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_248
#Given User enters keyword "capital and price or Algeria"
#Then  User verifies keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_249
#Given User enters keyword "fuel OR price AND Albania"
#Then  User verifies keyword search results 
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_250
#Given User enters keyword "fuel OR price and Albania"
#Then  User verifies keyword search results 
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_251
#Given User enters keyword "fuel or price and Albania"
#Then  User verifies keyword search results 
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_252
#Given User enters keyword "population OR India NOT average"
#Then  User verifies keyword search results 
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_253
#Given User enters keyword "population or India NOT average"
#Then  User verifies keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_254
#Given User enters keyword "population or India not average"
#Then  User verifies keyword search results  
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_255
#Given User enters keyword "gas NOT oil AND state"
#Then  User verifies keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_256
#Given User enters keyword "gas not oil AND state"
#Then  User verifies keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_257
#Given User enters keyword "gas not oil and state"
#Then  User verifies keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_258
#Given User enters keyword "gas NOT India OR state"
#Then  User verifies keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_259
#Given User enters keyword "gas NOT India or state"
#Then  User verifies keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_260
#Given User enters keyword "gas not India or state"
#Then  User verifies keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_261
#Given User enters keyword "Bank AND Deposits"
#Then  User verifies keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_262
#Given User enters keyword "Bank and Deposits"
#Then  User verifies keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_263
#Given User enters keyword "Bank And Deposits"
#Then  User verifies keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_264
#Given User enters keyword "Bank OR Deposits"
#Then  User verifies keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_265
#Given User enters keyword "Bank or Deposits"
#Then  User verifies keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_266
#Given User enters keyword "Bank oR Deposits"
#Then  User verifies keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_267
#Given User enters keyword "Bank NOT Deposits"
#Then  User verifies keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_268
#Given User enters keyword "Bank not Deposits"
#Then  User verifies keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_269
#Given User enters keyword "Bank Not Deposits"
#Then  User verifies keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_270
#Given User enters "IAPAFABH"
#Then  User verify the search results 
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_271
#Given User enters "134347308"
#Then  User verify the search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_272
#Given User enters keyword "Business AND Economic"
#Then  User verifies keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_273
#Given User enters keyword "Selenium OR Pottasium"
#Then  User verifies keyword search results
#
@KeywordSearch
Scenario: TC_KeywordSearch_274
Given User enters keyword "Cheese OR Honey"
Then  User verifies keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_275
#Given User enters "Agar;Methylene"
#Then  User verify the search results
##
#@KeywordSearch
#Scenario: TC_KeywordSearch_276
#Given User enters "Agar;BRDLAC;228912101"
#Then  User verify the search results
##
#@KeywordSearch
#Scenario: TC_KeywordSearch_277
#Given User enters "1380601"
#Then  User verify the search results
#
@KeywordSearch
Scenario: TC_KeywordSearch_278
Given User enters "State Bank of Mysore;shanghai stock exchange"
Then  User verify the search results

@KeywordSearch
Scenario: TC_Filters_Search_279
Given User enters "miner*;Seleni*"
Then  User verifies keyword search results  

@KeywordSearch
Scenario: TC_KeywordSearch_280
Given User enters "Mean;low"
Then  User verify the search results

@KeywordSearch
Scenario: TC_KeywordSearch_281
Given User enters "1000220125;1000205324;Low;High"
Then  User verify the search results

@KeywordSearch
Scenario: TC_KeywordSearch_282
Given User enters "134347308;IAPAFABH"
Then  User verify the search results

@KeywordSearch
Scenario: TC_KeywordSearch_283
Given User enters "134347308;Agar"
Then  User verify the search results

@KeywordSearch
Scenario: TC_KeywordSearch_284
Given User enters "134347308;IAPAFABH;Agar"
Then  User verify the search results

@KeywordSearch
Scenario: TC_KeywordSearch_285
Given User enters "228912101;crgabyu;honey;1380601;cheese;brjac"
Then  User verify the search results

@KeywordSearch
Scenario: TC_KeywordSearch_286
Given User enters keyword "State Bank of Mysore"
Then  User verify keyword search results

@KeywordSearch
Scenario: TC_KeywordSearch_287
Given User enters "Tes*"
Then  User verifies Filter search results  

@KeywordSearch
Scenario: TC_KeywordSearch_288
Given User enters keyword "agricultural machinery"
Then  User verify keyword search results

@KeywordSearch
Scenario: TC_KeywordSearch_289 : Search for an Acronym as "embi"
Given User enters keyword "embi"
Then  User verify keyword search results

@KeywordSearch
Scenario: TC_KeywordSearch_290 : Search for an Acronym as "real state"
Given User enters keyword "real state"
Then  User verify keyword search results

@KeywordSearch
Scenario: TC_KeywordSearch_291 : Search for an Acronym as "lme"
Given User enters keyword "lme"
Then User verify keyword search results

@KeywordSearch
Scenario: TC_KeywordSearch_292 : Search for an Acronym as "NCD"
Given User enters keyword "NCD"
Then User verify keyword search results

@KeywordSearch
Scenario: TC_KeywordSearch_293 : Search for an Acronym as "cis"
Given User enters keyword "cis"
Then User verify keyword search results

#@ChineseKeywordSearch
#Scenario: TC_KeywordSearch_294 : Search for an Acronym as "上交所"
#Given User enters keyword "上交所"
#Then User verify keyword search results
#
#@ChineseKeywordSearch
#Scenario: TC_KeywordSearch_295 : Search for an Acronym as "上海"
#Given User enters keyword "上海"
#Then User verify keyword search results
#
#@ChineseKeywordSearch
#Scenario: TC_KeywordSearch_296 : Search for an Acronym as "个人消费支出"
#Given User enters keyword "个人消费支出"
#Then User verify keyword search results
#
#@ChineseKeywordSearch
#Scenario: TC_KeywordSearch_297 : Search for an Acronym as "冰箱"
#Given User enters keyword "冰箱"
#Then User verify keyword search results
#
#@ChineseKeywordSearch
#Scenario: TC_KeywordSearch_298 : Search for an Acronym as "印尼"
#Given User enters keyword "印尼"
#Then User verify keyword search results
#
#@ChineseKeywordSearch
#Scenario: TC_KeywordSearch_299 : Search for an Acronym as "国债利率"
#Given User enters keyword "国债利率"
#Then User verify keyword search results
#
#@ChineseKeywordSearch
#Scenario: TC_KeywordSearch_300 : Search for an Acronym as "张家界"
#Given User enters keyword "张家界"
#Then User verify keyword search results
#
#@ChineseKeywordSearch
#Scenario: TC_KeywordSearch_301 : Search for an Acronym as "活猪存栏量"
#Given User enters keyword "活猪存栏量"
#Then User verify keyword search results
#
#@ChineseKeywordSearch
#Scenario: TC_KeywordSearch_302 : Search for an Acronym as "深交所"
#Given User enters keyword "深交所"
#Then User verify keyword search results
#
#@ChineseKeywordSearch
#Scenario: TC_KeywordSearch_303 : Search for an Acronym as "生产率"
#Given User enters keyword "生产率"
#Then User verify keyword search results
#
#@ChineseKeywordSearch
#Scenario: TC_KeywordSearch_304 : Search for an Acronym as "草鱼"
#Given User enters keyword "草鱼"
#Then User verify keyword search results
#
#@ChineseKeywordSearch
#Scenario: TC_KeywordSearch_305 : Search for an Acronym as "货币供应量"
#Given User enters keyword "货币供应量"
#Then User verify keyword search results
#
#@ChineseKeywordSearch
#Scenario: TC_KeywordSearch_306 : Search for an Acronym as "金融资产总量"
#Given User enters keyword "金融资产总量"
#Then User verify keyword search results
#
#@ChineseKeywordSearch
#Scenario: TC_KeywordSearch_307 : Search for an Acronym as "程限"
#Given User enters keyword "程2"
#Then User verify keyword search results
#
#@ChineseKeywordSearch
#Scenario: TC_KeywordSearch_308 : Search for an Acronym as "文化"
#Given User enters keyword "文化"
#Then User verify keyword search results
#
#@ChineseKeywordSearch
#Scenario: TC_KeywordSearch_309 : Search for an Acronym as "一月"
#Given User enters keyword "一月"
#Then User verify keyword search results
#
#@ChineseKeywordSearch
#Scenario: TC_KeywordSearch_310 : Search for an Acronym as "职工"
#Given User enters keyword "职工"
#Then User verify keyword search results
#
#@ChineseKeywordSearch
#Scenario: TC_KeywordSearch_311 : Search for an Acronym as "年尾年末"
#Given User enters keyword "年尾年末"
#Then User verify keyword search results
#
#@ChineseKeywordSearch
#Scenario: TC_KeywordSearch_312 : Search for an Acronym as "交易"
#Given User enters keyword "交易"
#Then User verify keyword search results
#
#@ChineseKeywordSearch
#Scenario: TC_KeywordSearch_313 : Search for an Acronym as "建造"
#Given User enters keyword "建造"
#Then User verify keyword search results
#
#@ChineseKeywordSearch
#Scenario: TC_KeywordSearch_314 : Search for an Acronym as "假期"
#Given User enters keyword "假期"
#Then User verify keyword search results
#
#@ChineseKeywordSearch
#Scenario: TC_KeywordSearch_315 : Search for an Acronym as "季节"
#Given User enters keyword "季节"
#Then User verify keyword search results
#
#@ChineseKeywordSearch
#Scenario: TC_KeywordSearch_316 : Search for an Acronym as "加强"
#Given User enters keyword "加强"
#Then User verify keyword search results
#
#@ChineseKeywordSearch
#Scenario: TC_KeywordSearch_317 : Search for an Acronym as "计算"
#Given User enters keyword "计算"
#Then User verify keyword search results
#
#@ChineseKeywordSearch
#Scenario: TC_KeywordSearch_318 : Search for an Acronym as "出产"
#Given User enters keyword "出产"
#Then User verify keyword search results
#
#@ChineseKeywordSearch
#Scenario: TC_KeywordSearch_319 : Search for an Acronym as "出入收支"
#Given User enters keyword "出入收支"
#Then User verify keyword search results
#
#@ChineseKeywordSearch
#Scenario: TC_KeywordSearch_320 : Search for an Acronym as "摩托车"
#Given User enters keyword "摩托车"
#Then User verify keyword search results
#
#@ChineseKeywordSearch
#Scenario: TC_KeywordSearch_321
#Given User enters "从业人数 AND ВВП"
#Then  User verifies keyword search results
#
#@ChineseKeywordSearch
#Scenario: TC_KeywordSearch_322
#Given User enters keyword "国内総生産 OR ВВП OR gas"
#Then  User verifies keyword search results 
#
#@RussianKeywordSearch
#Scenario: TC_KeywordSearch_323
#Given User enters keyword "среднегодовым"
#Then  User verify keyword search results 
#
#@ChineseKeywordSearch
#Scenario: TC_KeywordSearch_324
#Given User enters "摩托车"
#And   User selects "Source" as "China Association of Automobile Manufacturers"
#And   User has clicked on "Apply filter"
#Then  User verify the search results 
#
#@RussianKeywordSearch
#Scenario: TC_KeywordSearch_325
#Given User enters "среднегодовым"
#And   User selects "Source" as "Federal State Statistics Service"
#And   User has clicked on "Apply filter"
#Then  User verify the search results 
#
