Feature: Search

Background:
 	Given User has successful logged in
 	
#@KeywordSearch
#Scenario: TC_KeywordSearch_01 : Search for an Acronym as "GDP"
#Given User enters keyword "GDP"
#Then User verify keyword search results 
# 	
#@KeywordSearch
#Scenario: TC_KeywordSearch_02 : Search for an Acronym as "PMI" 
#Given User enters keyword "PMI"
#Then User verify keyword search results
#
#@KeywordSearch 
#Scenario: TC_KeywordSearch_03 : Search for an Acronym as "FLA"
#Given User enters keyword "FLA"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_04 : Search for an Acronym as "CPI"
#Given User enters keyword "CPI"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_05 : Search for an Acronym as "EFTA"
#Given User enters keyword "EFTA"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_06 : Search for an Acronym as "GIO"
#Given User enters keyword "GIO"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_07 : Search for an Acronym as "MMA"
#Given User enters keyword "MMA"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_08 : Search for an Acronym as "FAI"
#Given User enters keyword "FAI"
#Then User verify keyword search results

@KeywordSearch
Scenario: TC_KeywordSearch_09 : Search for an Acronym as "FDI"
Given User enters keyword "FDI"
Then User verify keyword search results

#@KeywordSearch
#Scenario: TC_KeywordSearch_10 : Search for an Acronym as "GCF"
#Given User enters keyword "GCF"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_11 : Search for an Acronym as "IMF"
#Given User enters keyword "IMF"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_12 : Search for an Acronym as "SOE"
#Given User enters keyword "SOE"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_13 : Search for an Acronym as "FOB"
#Given User enters keyword "FOB"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_14 : Search for an Acronym as "GNP"
#Given User enters keyword "GNP"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_15 : Search for an Acronym as "PPP"
#Given User enters keyword "PPP"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_16 : Search for an Acronym as "LCD"
#Given User enters keyword "LCD"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_17 : Search for an Acronym as "PCE"
#Given User enters keyword "PCE"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_18 : Search for an Acronym as "BIS"
#Given User enters keyword "BIS"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_19 : Search for an Acronym as "QFII"
#Given User enters keyword "QFII"
#Then User verify keyword search results
#
#@KeywordSearch
#Scenario: TC_KeywordSearch_20 : Search for an Acronym as "ICBC"
#Given User enters keyword "ICBC"
#Then User verify keyword search results
